/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jugador;

import helpers.Helpers;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author CodificatorGM - Hugo Ruben Norori Solano ~ hruns2000@gmail.com
 *
 */
public class Main extends javax.swing.JFrame {

    Jugador player;
    Jugador2 player2;
    String palabra = "";
    String nombre1;
    String nombre2;
    int turno2 = 7;
    int turno1 = 7;
    int puntos1 = 0;
    int puntos2 = 0;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        jPanel1.setBackground(new Color(0, 0, 0, 64));
        jPanel1.setOpaque(false);
        jPanel2.setBackground(new Color(0, 0, 0, 64));
        jPanel2.setOpaque(false);
        jPanel3.setBackground(new Color(0, 0, 0, 64));
        jPanel3.setOpaque(false);
        jPanel4.setBackground(new Color(0, 0, 0, 64));
        jPanel4.setOpaque(false);

        txtAdivinar.setBackground(new Color(64, 64, 64, 64));
        txtAdivinar2.setBackground(new Color(64, 64, 64, 64));
        txtPalabra.setBackground(new Color(64, 64, 64, 64));
        txtPista.setBackground(new Color(64, 64, 64, 64));

        btnAdivinarJ1.setEnabled(false);
        btnAdivinarJ2.setEnabled(false);
        btnMostrar.setEnabled(false);
        btnPalabra.setEnabled(false);
        btnReset.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtAdivinar = new javax.swing.JTextField();
        btnAdivinarJ1 = new javax.swing.JButton();
        lblJ1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAdivinarJ2 = new javax.swing.JButton();
        txtAdivinar2 = new javax.swing.JTextField();
        lblJ2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        lblPuntos2 = new javax.swing.JLabel();
        lblPuntos1 = new javax.swing.JLabel();
        lblPuntos3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTurnos2 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        lblTurnos1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnPalabra = new javax.swing.JButton();
        txtPalabra = new javax.swing.JPasswordField();
        lblChar4 = new javax.swing.JLabel();
        lblChar1 = new javax.swing.JLabel();
        lblChar6 = new javax.swing.JLabel();
        lblChar3 = new javax.swing.JLabel();
        lblChar5 = new javax.swing.JLabel();
        lblChar2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPista = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        exitmenu = new javax.swing.JMenu();
        btnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AHORCADO");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtAdivinar.setEditable(false);
        txtAdivinar.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        txtAdivinar.setForeground(new java.awt.Color(255, 255, 255));

        btnAdivinarJ1.setFont(new java.awt.Font("TempleOS", 0, 14)); // NOI18N
        btnAdivinarJ1.setText("ADIVINAR J1");
        btnAdivinarJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdivinarJ1ActionPerformed(evt);
            }
        });

        lblJ1.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        lblJ1.setForeground(new java.awt.Color(255, 204, 0));
        lblJ1.setText("J1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdivinarJ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblJ1)
                        .addGap(0, 180, Short.MAX_VALUE))
                    .addComponent(txtAdivinar))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblJ1)
                .addGap(38, 38, 38)
                .addComponent(txtAdivinar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnAdivinarJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 272, 230, 240));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnAdivinarJ2.setFont(new java.awt.Font("TempleOS", 0, 14)); // NOI18N
        btnAdivinarJ2.setText("ADIVINAR J2");
        btnAdivinarJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdivinarJ2ActionPerformed(evt);
            }
        });

        txtAdivinar2.setEditable(false);
        txtAdivinar2.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        txtAdivinar2.setForeground(new java.awt.Color(255, 255, 255));

        lblJ2.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        lblJ2.setForeground(new java.awt.Color(51, 255, 0));
        lblJ2.setText("J2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAdivinar2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblJ2)
                        .addGap(0, 180, Short.MAX_VALUE))
                    .addComponent(btnAdivinarJ2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblJ2)
                .addGap(35, 35, 35)
                .addComponent(txtAdivinar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnAdivinarJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 272, 230, 240));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Turnos:");

        lblPuntos.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        lblPuntos.setForeground(new java.awt.Color(0, 153, 153));
        lblPuntos.setText("Puntos:");

        lblPuntos2.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        lblPuntos2.setForeground(new java.awt.Color(204, 0, 51));
        lblPuntos2.setText("Puntos:");

        lblPuntos1.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        lblPuntos1.setForeground(new java.awt.Color(0, 153, 153));
        lblPuntos1.setText("N/A");

        lblPuntos3.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        lblPuntos3.setForeground(new java.awt.Color(204, 0, 51));
        lblPuntos3.setText("N/A");

        jLabel2.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Turnos:");

        lblTurnos2.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        lblTurnos2.setForeground(new java.awt.Color(204, 0, 51));
        lblTurnos2.setText("N/A");

        lblNombre.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 153, 153));
        lblNombre.setText("J1");

        lblNombre2.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        lblNombre2.setForeground(new java.awt.Color(204, 0, 51));
        lblNombre2.setText("J2");

        lblTurnos1.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        lblTurnos1.setForeground(new java.awt.Color(0, 153, 153));
        lblTurnos1.setText("N/A");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblPuntos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPuntos1))
                    .addComponent(lblNombre)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTurnos1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblPuntos2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPuntos3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTurnos2))
                    .addComponent(lblNombre2))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblNombre2))
                .addContainerGap(226, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPuntos2)
                            .addComponent(lblPuntos3))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblTurnos2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPuntos)
                            .addComponent(lblPuntos1))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblTurnos1))))
                .addGap(119, 119, 119))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 266));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("Letras");

        btnPalabra.setFont(new java.awt.Font("TempleOS", 0, 14)); // NOI18N
        btnPalabra.setText("INSERTAR PALABRA");
        btnPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalabraActionPerformed(evt);
            }
        });

        txtPalabra.setEditable(false);
        txtPalabra.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        txtPalabra.setForeground(new java.awt.Color(255, 255, 255));

        lblChar4.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        lblChar4.setForeground(new java.awt.Color(255, 204, 0));
        lblChar4.setText("4");

        lblChar1.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        lblChar1.setForeground(new java.awt.Color(0, 255, 0));
        lblChar1.setText("1");

        lblChar6.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        lblChar6.setForeground(new java.awt.Color(255, 204, 0));
        lblChar6.setText("6");

        lblChar3.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        lblChar3.setForeground(new java.awt.Color(0, 255, 0));
        lblChar3.setText("3");

        lblChar5.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        lblChar5.setForeground(new java.awt.Color(255, 204, 0));
        lblChar5.setText("5");

        lblChar2.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        lblChar2.setForeground(new java.awt.Color(0, 255, 0));
        lblChar2.setText("2");

        jLabel3.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("PALABRA");

        txtPista.setEditable(false);
        txtPista.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        txtPista.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("PISTA");

        btnMostrar.setFont(new java.awt.Font("TempleOS", 0, 14)); // NOI18N
        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnStart.setFont(new java.awt.Font("TempleOS", 0, 14)); // NOI18N
        btnStart.setText("START!");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("TempleOS", 0, 14)); // NOI18N
        btnReset.setText("RESET!");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblChar4)
                                    .addComponent(lblChar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblChar2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblChar5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblChar6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblChar3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnPalabra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPista)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3)
                                        .addComponent(txtPalabra)))
                                .addGap(0, 13, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChar2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChar3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChar5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChar6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChar4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 320, -1));

        jLabel7.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("I");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 30, -1));

        jLabel9.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("F");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 20, -1));

        jLabel10.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("C");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, -1, -1));

        jLabel11.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("I");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 20, 20));

        jLabel12.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("T");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 20, 20));

        jLabel13.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("D");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 319, 30, 30));

        jLabel14.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("O");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));

        jLabel15.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("O");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, -1, -1));

        jLabel16.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("R");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, -1));

        jLabel17.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 0));
        jLabel17.setText("A");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 20, -1));

        jLabel8.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("C");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        jLabel18.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 0));
        jLabel18.setText("Y");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        jLabel19.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 0));
        jLabel19.setText("B");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 30, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jugador/0568647e1b2161ce18d37a3fb6317155daeeba10_2_1024x584 (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));

        exitmenu.setText("Exit");
        exitmenu.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N

        btnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        btnExit.setFont(new java.awt.Font("TempleOS", 0, 16)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        exitmenu.add(btnExit);

        jMenuBar1.add(exitmenu);

        jMenu2.setText("About...");
        jMenu2.setFont(new java.awt.Font("TempleOS", 0, 18)); // NOI18N

        btnAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        btnAbout.setFont(new java.awt.Font("TempleOS", 0, 16)); // NOI18N
        btnAbout.setText("About");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        jMenu2.add(btnAbout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdivinarJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdivinarJ2ActionPerformed
        // TODO add your handling code here:

        String adivinar2 = txtAdivinar2.getText().toLowerCase().trim();

        if (!adivinar2.isEmpty()) {

            if (lblChar1.getText().trim().equalsIgnoreCase(String.valueOf(1))) {
                lblChar1.setText(adivinar2);
            } else if (lblChar2.getText().trim().equalsIgnoreCase(String.valueOf(2))) {
                lblChar2.setText(adivinar2);
            } else if (lblChar3.getText().trim().equalsIgnoreCase(String.valueOf(3))) {
                lblChar3.setText(adivinar2);
            } else if (lblChar4.getText().trim().equalsIgnoreCase(String.valueOf(4))) {
                lblChar4.setText(adivinar2);
            } else if (lblChar5.getText().trim().equalsIgnoreCase(String.valueOf(5))) {
                lblChar5.setText(adivinar2);
            } else if (lblChar6.getText().trim().equalsIgnoreCase(String.valueOf(6))) {
                lblChar6.setText(adivinar2);
            }

            if (player2.getTurno() > 1) {
                if (!palabra.contains(adivinar2)) {
                    turno2--;
                    player2.setTurno(turno2);
                    lblTurnos2.setText(String.valueOf(player2.getTurno()));
                    JOptionPane.showMessageDialog(null, "LETRA EQUIVACADA, TURNOS RESTANTES = " + String.valueOf(player2.getTurno()));
                }
                if (adivinar2.equalsIgnoreCase(palabra)) {
                    puntos2++;
                    player2.setPuntos(puntos2);
                    lblPuntos3.setText(String.valueOf(player2.getPuntos()));
                    JOptionPane.showMessageDialog(null, "PALABRA CORRECTA!!");
                    lblJ1.setText("J1");
                    lblJ2.setText("J2");
                    txtAdivinar.setText("");
                    txtAdivinar2.setText("");
                    txtPalabra.setText("");
                    txtPista.setText("");
                    palabra = "";
                    lblChar1.setText("1");
                    lblChar2.setText("2");
                    lblChar3.setText("3");
                    lblChar4.setText("4");
                    lblChar5.setText("5");
                    lblChar6.setText("6");

                    lblTurnos1.setText("7");
                    lblTurnos2.setText("7");
                    turno1 = 7;
                    turno2 = 7;
                    player.setTurno(turno1);
                    player2.setTurno(turno2);

                    if (player2.getPuntos() == 3) {
                        JOptionPane.showMessageDialog(null, "EL JUGADOR 2 HA GANADO!!!");
                    } else {
                        JOptionPane.showMessageDialog(null, "TURNO DEL JUGADOR 1 DE ADIVINAR LA PALABRA, EL JUGADOR 2 ESCRIBE");
                        txtAdivinar2.setEditable(false);
                        txtAdivinar.setEditable(true);
                        turno1 = 7;
                        turno2 = 7;
                        player.setTurno(turno1);
                        player2.setTurno(turno2);
                    }
                } else if (palabra.contains(adivinar2)) {

                    JOptionPane.showMessageDialog(null, "LETRA CORRECTA!!");

                }
            } else {
                turno2--;
                player2.setTurno(turno2);
                lblTurnos2.setText(String.valueOf(player2.getTurno()));
                JOptionPane.showMessageDialog(null, "SE HA QUEDADO SIN TURNOS, SIGUE EL OTRO JUGADOR");
                puntos1++;
                player.setPuntos(puntos1);
                lblPuntos1.setText(String.valueOf(player.getPuntos()));
                turno1 = 7;
                turno2 = 7;
                player.setTurno(turno1);
                player2.setTurno(turno2);
                txtAdivinar.setEditable(true);
                txtAdivinar2.setEditable(false);
                if (player.getPuntos() == 3) {
                    JOptionPane.showMessageDialog(null, "EL JUGADOR 1 HA GANADO!!!");
                }
                txtAdivinar2.setText("");
                txtAdivinar.setText("");
                txtPalabra.setText("");
                txtPista.setText("");
                palabra = "";
                lblChar1.setText("1");
                lblChar2.setText("2");
                lblChar3.setText("3");
                lblChar4.setText("4");
                lblChar5.setText("5");
                lblChar6.setText("6");

                lblJ1.setText("J1");
                lblJ2.setText("J2");
                txtAdivinar2.setEditable(false);
                txtAdivinar.setEditable(true);
                lblTurnos1.setText(String.valueOf(player.getTurno()));
                lblTurnos2.setText(String.valueOf(player2.getTurno()));
            }
            txtAdivinar2.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "NO HA INGRESADO UNA LETRA O PALABRA");
        }
    }//GEN-LAST:event_btnAdivinarJ2ActionPerformed

    private void btnPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalabraActionPerformed
        palabra = txtPalabra.getText().toLowerCase().trim();
        JOptionPane.showMessageDialog(null, "SE HA INSERTADO LA PALABRA, TURNO DEL JUGADOR QUE ADIVINA");
    }//GEN-LAST:event_btnPalabraActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        txtAdivinar.setText(palabra);
        txtAdivinar2.setText(palabra);
    }//GEN-LAST:event_btnMostrarActionPerformed
    private void btnAdivinarJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdivinarJ1ActionPerformed
        String adivinar = txtAdivinar.getText().toLowerCase().trim();

        if (!adivinar.isEmpty()) {

            if (lblChar1.getText().trim().equalsIgnoreCase(String.valueOf(1))) {
                lblChar1.setText(adivinar);
            } else if (lblChar2.getText().trim().equalsIgnoreCase(String.valueOf(2))) {
                lblChar2.setText(adivinar);
            } else if (lblChar3.getText().trim().equalsIgnoreCase(String.valueOf(3))) {
                lblChar3.setText(adivinar);
            } else if (lblChar4.getText().trim().equalsIgnoreCase(String.valueOf(4))) {
                lblChar4.setText(adivinar);
            } else if (lblChar5.getText().trim().equalsIgnoreCase(String.valueOf(5))) {
                lblChar5.setText(adivinar);
            } else if (lblChar6.getText().trim().equalsIgnoreCase(String.valueOf(6))) {
                lblChar6.setText(adivinar);
            }
            if (player.getTurno() > 1) {
                if (!palabra.contains(adivinar)) {
                    turno1--;
                    player.setTurno(turno1);
                    lblTurnos1.setText(String.valueOf(player.getTurno()));
                    JOptionPane.showMessageDialog(null, "LETRA EQUIVACADA, TURNOS RESTANTES = " + String.valueOf(player.getTurno()));
                }
                if (adivinar.equalsIgnoreCase(palabra)) {
                    puntos1++;
                    player.setPuntos(puntos1);
                    lblPuntos1.setText(String.valueOf(player.getPuntos()));
                    JOptionPane.showMessageDialog(null, "PALABRA CORRECTA!!");
                    lblJ1.setText("J1");
                    lblJ2.setText("J2");
                    txtAdivinar.setText("");
                    txtPalabra.setText("");
                    txtPista.setText("");
                    palabra = "";
                    lblChar1.setText("1");
                    lblChar2.setText("2");
                    lblChar3.setText("3");
                    lblChar4.setText("4");
                    lblChar5.setText("5");
                    lblChar6.setText("6");

                    lblTurnos1.setText("7");
                    lblTurnos2.setText("7");
                    turno1 = 7;
                    turno2 = 7;
                    player.setTurno(turno1);
                    player2.setTurno(turno2);
                    if (puntos1 == 3) {
                        JOptionPane.showMessageDialog(null, "EL JUGADOR 1 HA GANADO!!!");
                    } else {
                        JOptionPane.showMessageDialog(null, "TURNO DEL JUGADOR 2 DE ADIVINAR LA PALABRA, EL JUGADOR 1 ESCRIBE");
                        txtAdivinar.setEditable(false);
                        txtAdivinar2.setEditable(true);
                        turno1 = 7;
                        turno2 = 7;
                        player.setTurno(turno1);
                        player2.setTurno(turno2);
                    }
                } else if (palabra.contains(adivinar)) {
                    JOptionPane.showMessageDialog(null, "LETRA CORRECTA!!");
                }
            } else {
                turno1--;
                player.setTurno(turno1);
                lblTurnos1.setText(String.valueOf(player.getTurno()));
                turno1 = 7;
                turno2 = 7;
                player.setTurno(turno1);
                player2.setTurno(turno2);
                JOptionPane.showMessageDialog(null, "SE HA QUEDADO SIN TURNOS, SIGUE EL OTRO JUGADOR");
                puntos2++;
                player2.setPuntos(puntos2);
                lblPuntos3.setText(String.valueOf(player2.getPuntos()));
                txtAdivinar.setEditable(false);
                txtAdivinar2.setEditable(true);
                if (player2.getPuntos() == 3) {
                    JOptionPane.showMessageDialog(null, "EL JUGADOR 2 HA GANADO!!!");
                }
                txtAdivinar.setText("");
                txtPalabra.setText("");
                txtPista.setText("");
                palabra = "";
                lblChar1.setText("1");
                lblChar2.setText("2");
                lblChar3.setText("3");
                lblChar4.setText("4");
                lblChar5.setText("5");
                lblChar6.setText("6");

                lblJ1.setText("J1");
                lblJ2.setText("J2");
                lblTurnos1.setText(String.valueOf(player.getTurno()));
                lblTurnos2.setText(String.valueOf(player2.getTurno()));
            }
            txtAdivinar.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "NO HA INGRESADO UNA LETRA O PALABRA");
    }
    }//GEN-LAST:event_btnAdivinarJ1ActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        nombre1 = JOptionPane.showInputDialog(null, "INGRESE NOMBRE #1 JUGADOR");
        nombre2 = JOptionPane.showInputDialog(null, "INGRESE NOMBRE #2 JUGADOR");
        puntos1 = 0;
        puntos2 = 0;
        turno1 = 7;
        turno2 = 7;

        lblTurnos1.setText("7");
        lblTurnos2.setText("7");

        player = new Jugador(nombre1, turno1, puntos1);
        player2 = new Jugador2(nombre2, turno2, puntos2);

        lblNombre.setText(player.getNombre());
        lblNombre2.setText(player2.getNombre());
        lblPuntos1.setText(String.valueOf(puntos1));
        lblPuntos3.setText(String.valueOf(puntos2));

        txtAdivinar2.setEditable(true);
        txtPalabra.setEditable(true);
        txtPista.setEditable(true);

        btnAdivinarJ1.setEnabled(true);
        btnAdivinarJ2.setEnabled(true);
        btnMostrar.setEnabled(true);
        btnPalabra.setEnabled(true);
        btnReset.setEnabled(true);
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed

        lblNombre.setText("J1");
        lblNombre2.setText("J2");
        lblPuntos1.setText("N/A");
        lblPuntos3.setText("N/A");
        txtAdivinar.setText("");
        txtAdivinar2.setText("");
        txtPalabra.setText("");
        txtPista.setText("");
        palabra = "";
        lblChar1.setText("1");
        lblChar2.setText("2");
        lblChar3.setText("3");
        lblChar4.setText("4");
        lblChar5.setText("5");
        lblChar6.setText("6");

        lblJ1.setText("J1");
        lblJ2.setText("J2");
        lblTurnos1.setText("7");
        lblTurnos2.setText("7");
        turno1 = 7;
        turno2 = 7;
        txtAdivinar.setEditable(false);
        txtAdivinar2.setEditable(false);
        txtPalabra.setEditable(false);
        txtPista.setEditable(false);

        txtAdivinar.setBackground(new Color(64, 64, 64, 64));
        txtAdivinar2.setBackground(new Color(64, 64, 64, 64));
        txtPalabra.setBackground(new Color(64, 64, 64, 64));
        txtPista.setBackground(new Color(64, 64, 64, 64));

        player = new Jugador();
        player2 = new Jugador2();

        btnAdivinarJ1.setEnabled(false);
        btnAdivinarJ2.setEnabled(false);
        btnMostrar.setEnabled(false);
        btnPalabra.setEnabled(false);
        btnReset.setEnabled(false);

    }//GEN-LAST:event_btnResetActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:

        Helpers help = new Helpers();
        help.abrirArchivo("C:\\Users\\Dell PC\\Documents\\NetBeansProjects\\Ahorcado\\About\\CREDITS.txt");
    }//GEN-LAST:event_btnAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAbout;
    private javax.swing.JButton btnAdivinarJ1;
    private javax.swing.JButton btnAdivinarJ2;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnPalabra;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStart;
    private javax.swing.JMenu exitmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblChar1;
    private javax.swing.JLabel lblChar2;
    private javax.swing.JLabel lblChar3;
    private javax.swing.JLabel lblChar4;
    private javax.swing.JLabel lblChar5;
    private javax.swing.JLabel lblChar6;
    private javax.swing.JLabel lblJ1;
    private javax.swing.JLabel lblJ2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JLabel lblPuntos1;
    private javax.swing.JLabel lblPuntos2;
    private javax.swing.JLabel lblPuntos3;
    private javax.swing.JLabel lblTurnos1;
    private javax.swing.JLabel lblTurnos2;
    private javax.swing.JTextField txtAdivinar;
    private javax.swing.JTextField txtAdivinar2;
    private javax.swing.JPasswordField txtPalabra;
    private javax.swing.JTextField txtPista;
    // End of variables declaration//GEN-END:variables
}
